AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function Definition

Resources:
  snSLABSLambda:
    Type: AWS::Lambda::Function
    DependsOn: snSLABSRole
    Properties:
      Handler: index.handler
      FunctionName: snSLABSLambda
      Role: !GetAtt snSLABSRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3BucketName
        S3Key: !Ref LambdaFileKey
      Environment:
        Variables:
          ssm_configuration_path: /com.servicenow.cti/946403cfdb8c80180ae3ac44d4961982/SLABS/default
          provider_id: c4b12aa6e700001034b36584c2f6a9bc
      Runtime: nodejs18.x
      Timeout: '30'

  snSLABSLambdaLexPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt snSLABSLambda.Arn
      Principal: lex.amazonaws.com
      SourceArn: !Sub 'arn:aws:lex:${AWS::Region}:${AWS::AccountId}:intent:*'