AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda IAM Policy

Resources:
  snSLABSPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - snSLABSLambdaLogGroup
      - snSLABSKinesisStream
    Properties:
      PolicyName: snSLABSLambdaCloudWatchPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: InlinePolicy0
            Effect: Allow
            Action:
              - kms:Decrypt
              - kinesis:ListStreams
            Resource: '*'
          - Sid: InlinePolicy1
            Effect: Allow
            Action:
              - s3:GetObject
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ssm:GetParametersByPath
            Resource:
              - !Sub
                - 'arn:aws:s3:::${callBucket}/*'
                - callBucket: !Ref CallRecordingBucketName
              - !Sub
                - 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${loggroup}:log-stream:*'
                - loggroup: !Ref snSLABSLambdaLogGroup
              - !Sub
                - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${defaultParam}'
                - defaultParam: com.servicenow.cti/946403cfdb8c80180ae3ac44d4961982/SLABS/default
          - Sid: InlinePolicy2
            Effect: Allow
            Action:
              - kinesis:GetRecords
              - kinesis:GetShardIterator
              - kinesis:DescribeStream
            Resource:
              - !GetAtt snSLABSKinesisStream.Arn
      Roles:
        - !Ref snSLABSRole