AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack calling nested stacks for ServiceNow Cloud Call Center

Parameters:
  LambdaS3BucketName:
    Type: String
    Description: S3 Bucket Name where Lambda.zip is uploaded
  CallRecordingBucketName:
    Type: String
    Description: Provide the call recording Bucket Name
  ProviderId:
    Type: String
    Default: c4b12aa6e700001034b36584c2f6a9bc
    Description: This is provider id in Snow voice assist.

Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${LambdaS3BucketName}.s3.${AWS::Region}.amazonaws.com/iam-resources.yaml"

  KinesisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${LambdaS3BucketName}.s3.${AWS::Region}.amazonaws.com/kinesis-resources.yaml"

  SSMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${LambdaS3BucketName}.s3.${AWS::Region}.amazonaws.com/ssm-parameters.yaml"
      Parameters:
        ProviderId: !Ref ProviderId

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - KinesisStack
      - SSMStack
    Properties:
      TemplateURL: https://test-f123.s3.ap-northeast-1.amazonaws.com/lambda-resources.yaml
      Parameters:
        LambdaS3BucketName: !Ref LambdaS3BucketName
        CallRecordingBucketName: !Ref CallRecordingBucketName
        RoleArn: !GetAtt IAMStack.Outputs.RoleArn
        RoleName: !GetAtt IAMStack.Outputs.RoleName
        KinesisStreamArn: !GetAtt KinesisStack.Outputs.KinesisStreamArn
        DefaultConfigArn: !GetAtt SSMStack.Outputs.DefaultConfigArn
        ProviderId: !Ref ProviderId
