AWSTemplateFormatVersion: '2010-09-09'
Description: Kinesis Stream Definition

Resources:
  snSLABSKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: snSLABSKinesisStream
      ShardCount: '1'

  snSLABSEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn:
      - snSLABSLambda
      - snSLABSPolicy
    Properties:
      EventSourceArn: !Sub
        - 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${kinesisstream}'
        - kinesisstream: !Ref snSLABSKinesisStream
      FunctionName: !GetAtt snSLABSLambda.Arn
      StartingPosition: TRIM_HORIZON