AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Policy for ServiceNow Cloud Call Center Stack Deployment

Resources:
  CloudFormationDeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for deploying ServiceNow Cloud Call Center stack
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:PassRole
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
            Resource: '*'
          - Effect: Allow
            Action:
              - lambda:*
            Resource: '*'
          - Effect: Allow
            Action:
              - kinesis:*
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: '*'
          - Effect: Allow
            Action:
              - ssm:*
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub 'arn:aws:s3:::${AWS::AccountId}-${AWS::Region}-sam'
              - !Sub 'arn:aws:s3:::${AWS::AccountId}-${AWS::Region}-sam/*'