AWSTemplateFormatVersion: '2010-09-09'
Description: Kinesis Stream for ServiceNow CTI

Resources:
  snSLABSKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: snSLABSKinesisStream
      ShardCount: 1

Outputs:
  KinesisStreamArn:
    Description: ARN of the Kinesis Stream
    Value: !GetAtt snSLABSKinesisStream.Arn
