AWSTemplateFormatVersion: '2010-09-09'
Description: Common parameters for ServiceNow CTI

Parameters:
  # Lambda code location
  LambdaS3BucketName:
    Type: String
    Description: S3 bucket where Lambda.zip is uploaded
  LambdaFileKey:
    Type: String
    Description: S3 key for Lambda ZIP artifact

  # Call recording bucket
  CallRecordingBucketName:
    Type: String
    Description: S3 bucket name to store call recordings