AWSTemplateFormatVersion: '2010-09-09'
Description: Root template that orchestrates nested stacks for ServiceNow CTI

Parameters:
  LambdaS3BucketName:
    Type: String
    Description: S3 bucket where Lambda.zip is uploaded
  LambdaFileKey:
    Type: String
    Description: S3 key for Lambda ZIP artifact
  CallRecordingBucketName:
    Type: String
    Description: S3 bucket name to store call recordings

Resources:
  # Data layer must deploy first to export Kinesis stream and LogGroup
  DataLayerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./data-layer.yaml

  # Security layer imports exported ARNs from DataLayerStack
  SecurityLayerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataLayerStack
    Properties:
      TemplateURL: ./security-layer.yaml
      Parameters:
        CallRecordingBucketName: !Ref CallRecordingBucketName

  # Compute layer depends on Data and Security layers
  ComputeLayerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataLayerStack
      - SecurityLayerStack
    Properties:
      TemplateURL: ./compute-layer.yaml
      Parameters:
        LambdaS3BucketName: !Ref LambdaS3BucketName
        LambdaFileKey:      : !Ref LambdaFileKey
        snSLABSRoleArn:     : !GetAtt SecurityLayerStack.Outputs.snSLABSRoleArn

  # Integration layer depends on Compute layer
  IntegrationLayerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeLayerStack
    Properties:
      TemplateURL: ./integration-layer.yaml
      Parameters:
        snSLABSLambdaArn: !GetAtt ComputeLayerStack.Outputs.snSLABSLambdaArn