AWSTemplateFormatVersion: '2010-09-09'
Description: SSM Parameters for ServiceNow CTI configuration

Resources:
  snSLABSDefaultConfigurationProfile:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ServiceNow settings for the CTI REST endpoint.
      Name: /com.servicenow.cti/946403cfdb8c80180ae3ac44d4961982/SLABS/default
      Type: String
      Value: |
        {
            required: {
                host: {
                    description: "The ServiceNow host that connect proxy will talk to"
                    value: "instance.service-now.com"
                },
                service_account_user: {
                    description: "Service account username for CTI REST Endpoint"
                },
                service_account_password: {
                    description: "Service account password for CTI REST Endpoint"
                }
            },
            optional: {
                provider_id: {
                    description: "CTI REST endpoint provider id",
                    value: "c4b12aa6e700001034b36584c2f6a9bc"
                }
            }
        }

  snSLABSCtiRestHost:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ServiceNow instance that contains your CTI REST endpoint
      Name: /com.servicenow.cti/946403cfdb8c80180ae3ac44d4961982/SLABS/default/host
      Type: String
      Value: nttpccomdev2.service-now.com

Outputs:
  DefaultConfigArn:
    Description: ARN of the default configuration parameter
    Value: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${snSLABSDefaultConfigurationProfile}"
  CtiHostArn:
    Description: ARN of the CTI host parameter
    Value: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${snSLABSCtiRestHost}"
