AWSTemplateFormatVersion: '2010-09-09'
Description: Kinesis Stream for ServiceNow CTI

Resources:
  snLambdaKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: snLambdaKinesisStream
      ShardCount: 1

Outputs:
  KinesisStreamArn:
    Description: ARN of the Kinesis Stream
    Value: !GetAtt snLambdaKinesisStream.Arn
